version = 1

[[analyzers]]
name = "sql"
enabled = false

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["docker/Dockerfile"]

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "php"
enabled = false

[[analyzers]]
name = "java"
enabled = false

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"
enabled = false

[[analyzers]]
name = "terraform"
enabled = false

[[analyzers]]
name = "javascript"
enabled = false

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dependency_file_paths = [
    'javascript/packages/demo-react/',
    'javascript/packages/demo-vue/',
    'javascript/packages/demo-next/',
    'javascript/packages/demo-nuxt/',
    'javascript/packages/demo-typescript/'
  ]

[[analyzers]]
name = "ruby"
enabled = false

[[analyzers]]
name = "go"
enabled = false

  [analyzers.meta]
  import_root = "github.com/QuackatronHQ/Gigarepo"

[[analyzers]]
name = "python"
enabled = false

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = false

[[transformers]]
name = "rustfmt"
enabled = false

[[transformers]]
name = "php-cs-fixer"
enabled = false

[[transformers]]
name = "google-java-format"
enabled = false

[[transformers]]
name = "prettier"
enabled = false

[[transformers]]
name = "rubocop"
enabled = false

[[transformers]]
name = "gofmt"
enabled = false

[[transformers]]
name = "black"
enabled = false

[[transformers]]
name = "isort"
enabled = false

[[transformers]]
name = "autopep8"
enabled = false

[[transformers]]
name = "yapf"
enabled = false

[[transformers]]
name = "gofumpt"
enabled = false

[[transformers]]
name = "standardrb"
enabled = false

[[transformers]]
name = "standardjs"
enabled = false
